In [2]:
import numpy as np

In [7]:
import matplotlib.pyplot as plt

In [11]:
# 一维
a = np.array([1,2,3])
print(a)

# 等间隔数字的数组
b = np.arange(10)
print(b)

[1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [19]:
# ndmin指定返回数组的最小维数
d = np.array([1,2,3,4,5])
print(d)
e = np.array([1,2,3,4,5,6],ndmin = 5)
print(e)
print([[2]])
f = np.array([1,2,3,4,5,6], dtype = complex)
print(f)

[1 2 3 4 5]
[[[[[1 2 3 4 5 6]]]]]
[[2]]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j]


In [22]:
g = np.dtype(np.int32)
print(g)
h = np.dtype("i8")
print(h)

int32
int64


In [27]:
i = np.array([[1,2,3],[4,5,6]])
print(i)
i.shape = (6,1)
print(i)

[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [35]:
j = np.arange(24)
print(j)
print(j.ndim)
j.shape =(2,2,6)
print(j.ndim)
print(j.dtype)
print(j.itemsize)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
3
int32
4


In [63]:
k = np.empty([3,2],dtype ="i1")
print(k)

[[-48   1]
 [-66  84]
 [  0   0]]


In [69]:
l = np.zeros([5,6],dtype = "i4")
print(l)
print(l.dtype)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
int32


In [72]:
m = np.ones([2,3])
print(m)

[[1. 1. 1.]
 [1. 1. 1.]]


In [75]:
x = [1,2,3]
print(np.asarray(x))

[1 2 3]


In [82]:
y = range(5)
print(y)
print(iter(y))
print(np.fromiter(iter(y),dtype="float")) # 必须要有 dtype

range(0, 5)
[0. 1. 2. 3. 4.]


In [84]:
print(np.arange(10,20,2))

[10 12 14 16 18]


In [89]:
print(np.linspace(10,20,30,endpoint = False))
print(np.linspace(10,20,30,retstep = True))

[10.         10.33333333 10.66666667 11.         11.33333333 11.66666667
 12.         12.33333333 12.66666667 13.         13.33333333 13.66666667
 14.         14.33333333 14.66666667 15.         15.33333333 15.66666667
 16.         16.33333333 16.66666667 17.         17.33333333 17.66666667
 18.         18.33333333 18.66666667 19.         19.33333333 19.66666667]
(array([10.        , 10.34482759, 10.68965517, 11.03448276, 11.37931034,
       11.72413793, 12.06896552, 12.4137931 , 12.75862069, 13.10344828,
       13.44827586, 13.79310345, 14.13793103, 14.48275862, 14.82758621,
       15.17241379, 15.51724138, 15.86206897, 16.20689655, 16.55172414,
       16.89655172, 17.24137931, 17.5862069 , 17.93103448, 18.27586207,
       18.62068966, 18.96551724, 19.31034483, 19.65517241, 20.        ]), 0.3448275862068966)


In [93]:
z = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(z[...,0])

[1 4 7]
